### ISSUE TITLE
Specify the dataset and the hyperparameters in the main.py file

### ISSUE THREAD

**Issue by bousejin** [giannisnik/cnn-graph-classification#1]
Hi there. Thank you for the code. In which line in the main.py file can I specify the dataset and the hyperparameters? When I run python main.py it gives me the error below:

Computing graph maps
Number of communities:  2594
Average size: 7.52
Traceback (most recent call last):
  File "main.py", line 280, in <module>
    main()
  File "main.py", line 62, in main
    Q, subgraphs, labels, shapes = compute_nystrom(args.dataset, use_node_labels, args.d, args.community_detection, kernels)
  File "/home/n/Documents/GDL/cnn-graph-classification/kcnn/utils.py", line 152, in compute_nystrom
    model.fit(communities)
  File "/home/n/Documents/GDL/cnn-graph-classification/kcnn/nystrom.py", line 30, in fit
    basis_kernel = self.kernel(basis, basis, **self._get_kernel_params())
  File "/home/n/Documents/GDL/cnn-graph-classification/kcnn/graph_kernels.py", line 111, in wl_kernel
    if len(neighbors) > 0:
TypeError: object of type 'generator' has no len()

**Comment by bousejin** [comment]
Thanks, but I changed line 110 of graph_kernels.py to:

neighbors = list(G.neighbors(node))

and it worked.

**Comment by xanawang** [comment]
I ran this program by pytorch 0.4.0 which is the only Windows supported version.
It seems that Variable is deprecated in pytorch 0.4.0, I had to delete line 42-44 in init.py to avoid maximum recursion depth error.
However, I got the results like Average accuracy always 0.000, Average loss always around 1,and no best model found.
Is there something I did wrong...?

**Comment by xanawang** [comment]
I ran this program by pytorch 0.4.0 which is the only Windows supported version.
It seems that Variable is deprecated in pytorch 0.4.0, I had to delete line 42-44 in init.py to avoid maximum recursion depth error.
However, I got the results like Average accuracy always 0.000, Average loss always around 1,and no best model found.
Is there anything I did wrong...?

**Comment by giannisnik** [comment]
Hi @xanawang. I am very sorry I cnnot help you since I am not familiar with PyTorch 0.4.0. I will try to update the code to PyTorch 0.4.0 in a few weeks though.
