### ISSUE TITLE
np.vstack

### ISSUE THREAD

**Issue by penguinbear** [giannisnik/cnn-graph-classification#4]
Hi @giannisnik ,

Could you please shed some light on why to append a zero row on top of Q_t?
`Q_t = np.vstack([np.zeros(embedding_dim), Q_t])`   # Line 154 in utils.py

Thanks.

**Comment by giannisnik** [comment]
Hi @penguinbear. Each graph is represented as a sequence of the ids of its communities. These ids are the replaced with the vector representation of the corresponding communities. Some graphs contain more communities than others. All graphs are padded with the zero id to have the same length (in terms of number of communities). This all-zeros row corresponds to the representation of these zero id communities.
