### ISSUE TITLE
Problem with len(neighbors)

### ISSUE THREAD

**Issue by FernandoLpz** [giannisnik/cnn-graph-classification#9]
https://github.com/giannisnik/cnn-graph-classification/blob/a63ef4b192ca014f3e386b7cd59fa61fded53527/kcnn/graph_kernels.py#L111
@giannisnik 
There is an issue when I run the code, it seems you are trying to get the "len" from some "generator object".  
<img width="411" alt="captura de pantalla 2019-01-14 a la s 16 35 18" src="https://user-images.githubusercontent.com/22309930/51145739-66894800-181a-11e9-9ce4-f54ac9cca5e1.png">

**Comment by giannisnik** [comment]
Hi @FernandoLpz . This is because your NetworkX version is 2.X instead of 1.11 . You can either downgrade to NetworkX 1.11 or replace that line with: if len(list(neighbors)) > 0:

**Comment by FernandoLpz** [comment]
> Hi @FernandoLpz . This is because your NetworkX version is 2.X instead of 1.11 . You can either downgrade to NetworkX 1.11 or replace that line with: if len(list(neighbors)) > 0:

It works! Thanks!
